### PR TITLE
Rw shoppingcart

### PR DESCRIPTION
**Pull request by rtwhitfield84**
## Description
This pull request covers the addition of a users shopping cart total across the relevant views.

## Related Ticket(s)
#36 
#7

## Problem to Solve
Users needed to be able to see there shopping cart total in the navbar

## Changes
added try and except to each necessary view in order test wether a customer had an order and if so display the current total in the navbar.

## Expected Behavior
Product total should be visible in each user authenticated view

## Steps to Test Solution
```
git fetch
git checkout rw-shoppingcart
```

login or register a user.
create an order
see that order total updates

## Unit Testing
- [ ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
- [] I certify that all existing tests pass

## Documentation

- [ ] There is new documentation in this pull request that must be reviewed..
- [ ] I added documentation for any new classes/methods

### CODE REVIEW

**Comment by samphillips1879** [comment]
got an error after logging in:

**"MultipleObjectsReturned at /categories/
get() returned more than one CustomerOrder -- it returned 9!"**

I think this is caused by the user I was logged in as having multiple closed orders
This can PROBABLY be fixed by adjusting your query. Perhaps try changing
```
self.cart = CustomerOrder.objects.get(customer=request.user.customer)
```
to
```
self.cart = CustomerOrder.objects.filter(customer=request.user.customer, active_order=1)
```

ALSO

```render``` needs to be imported in the order_success view, and any other view which will contain the cart info in the navbar that isn't already importing ```render```.

Other than that, your core logic seems to be sound. It was working fine with a new customer until I got to the order success view.

**Comment by samphillips1879** [comment]
Perfect 👍 works flawlessly on my machine

**Comment by samphillips1879** [comment]
That is one nice :shopping_cart:

**Comment by whitneycormack** [comment]
:shopping_cart: 🎉 👍 looks great!

**Pull request merged**
