### PR TITLE
update total quantity of inventory after products are purchased

### PR DESCRIPTION
**Pull request by whitneycormack**
## Description
Add description about what this pull request covers.
total inventory of product is now updated when someone purchases a product
ie. there are 200 plates & customer purchases 100, after they checkout, there are now only 100 plates left to purchase

## Number of Fixes
List of fixes included in this PR.

## Related Ticket(s)
List related ticket(s) that apply to the work done in this pull request
#64 

## Problem to Solve
Describe the problem(s) this pull request solves.
inventory was not true to what customers had already purchased

## Changes
Describe the proposed changes, if any.
n/a

## Expected Behavior
Describe the expected behavior.
when you navigate through the site and purchase products, ensure that the quantity updates (on the product detail page, the dropdown should reflect updated inventory) once you checkout

## Steps to Test Solution
List steps to test your solution
fetch wc-quantityupdate
checkout wc-quantityupdate
python manage.py runserver

### CODE REVIEW

**Comment by samphillips1879** [comment]
Works as it should 👍 :orthodox_cross: 🏮

**Comment by samphillips1879** [comment]
🚛

**Comment by samphillips1879** [comment]
🏩

**Comment by samphillips1879** [comment]
:eagle: :place_of_worship:

**Review by rtwhitfield84 — APPROVED** [review]
👍 🚢 🤖

**Pull request merged**
